geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf.urls import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('mainapp.urls', namespace='product')),
    path('contact/', mainapp.contact, name='contact'),
    path('', mainapp.main, name='home'),
]

# Только на время разработки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.product, name='index'),
    # path('<str:href>/', mainapp.product, name='what_is_it'),
    path('<int:pk>/', mainapp.product, name='category'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Назвние', unique=True, max_length=60)
    description = models.TextField(verbose_name='Описание', blank=True)
    href = models.CharField(verbose_name='Ссылка', unique=True, max_length=10, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название', unique=True, max_length=60)
    short_description = models.TextField(verbose_name='Краткое описание', max_length=128)
    description = models.TextField(verbose_name='Описание', blank=True)
    image = models.ImageField(upload_to='products_imgs', blank=True, verbose_name='Фото')
    price = models.DecimalField(null=True, verbose_name='Цена', max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(null=True, verbose_name='Количество')

    def __str__(self):
        return f'{self.name} {self.category.name}'


class Contacts(models.Model):
    city = models.CharField(verbose_name='Город', max_length=30)
    phone = models.CharField(verbose_name='Телефон (формат: +7-888-888-8888)', max_length=15)
    email = models.CharField(verbose_name='Почта', max_length=64)
    address = models.CharField(verbose_name='Адрес', max_length=64)

geekshop/mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product, Contacts


def main(request):
    content = {
        'title': 'главная',
        'products': Product.objects.all()
    }
    return render(request, 'mainapp/index.html', content)


def contact(request):
    content = {
        'title': 'контакты',
        'contacts': Contacts.objects.all()
    }
    return render(request, 'mainapp/contact.html', content)


def product(request, pk=None):
    content = {
        'title': 'продукты',
        # Похожие товары
        'products': [
            {
                'src': '/img/product-11.jpg',
                'title': 'Стул повышенного качества',
                'second_title': 'Не оторваться.'
            },
            {
                'src': '/img/product-21.jpg',
                'title': 'Стул повышенного качества',
                'second_title': 'Не оторваться.'
            },
            {
                'src': '/img/product-31.jpg',
                'title': 'Стул повышенного качества',
                'second_title': 'Не оторваться.'
            },
        ],
        'categories': ProductCategory.objects.all()
    }
    return render(request, 'mainapp/products.html', content)

geekshop/authapp/templates/authapp/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

geekshop/authapp/templates/authapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

geekshop/authapp/templates/authapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

geekshop/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    {% block js %}
    {% endblock js%}

    {% block title %}
    {% endblock title %}

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock css %}
</head>

<body>
<div class="container">
    {% block content %}
    {% endblock content %}
    <div class="clr"></div>
</div>

{% block footer %}
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB {% now 'Y' %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>
{% endblock footer %}

</body>
</html>

geekshop/mainapp/templates/mainapp/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
<title>{{ title|title }}</title>
{% endblock title %}

{% block content %}
<div class="hero">
    {% include 'mainapp/menu.html' %}
    <h1>наши контакты</h1>
</div>

<div class="location">
    {% for contact in contacts %}
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>{{ contact.city }}</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>{{ contact.phone }}</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>{{ contact.email }}</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>{{ contact.address }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
<title>{{ title|title }}</title>
{% endblock title %}

{% block content %}
<div class="slider">
    {% include 'mainapp/menu.html' %}
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">заказать <img src="{% static '/img/arrow.png' %}" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>

<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="{% static '/img/arrow.png' %}" alt=""></a>
    <div class="clearfix"></div>

    <div class="tab-content">
        {% for product in products %}
        <div class="block">
            <a href="#"><img src="/media/{{ product.image }}" width=270px height=270px>
                <div class="text">
                    <img src="{% static 'img/arrow.png' %}">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_description }}</p>
                </div>
            </a>
        </div>
        {% endfor  %}
    </div>
    <div class="clr"></div>
</div>
{% endblock content %}

geekshop/mainapp/templates/mainapp/menu.html
<div class="header clearfix">
    <a href="{% url 'home' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'home' %}" class="{% if title == 'главная' %}active{% endif %}">домой</a></li>
        <li><a href="{% url 'product:index' %}" class="{% if title == 'продукты' %}active{% endif %}">продукты</a></li>
        <li><a href="{% url 'contact' %}" class="{% if title == 'контакты' %}active{% endif %}">контакты</a></li>
    </ul>
    <a href="#" class="search"></a>
    <a href="#" class="basket"></a>
</div>

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
<title>{{ title|title }}</title>
{% endblock title %}

{% block content %}
<div class="hero-white">
    {% include 'mainapp/menu.html' %}
</div>

<div class="details">
    <div class="links clearfix">
        <ul class="links-menu">
            {% for category in categories %}
            <li><a href="#" class="active">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="{% static '/img/slider1.jpg' %}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="{% static '/img/controll.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static '/img/controll1.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static '/img/controll2.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">Отличный стул</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> 2585.9 <span>руб</span></p>
            <a href="#" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>Расположитесь комфортно.</p>
                <p>Отличное качество материалов
                    позволит вам это.</p>
                <p>Различные цвета</p>
                <p>высочайший уровень
                    эргономики и прочность.</p>
            </div>
        </div>
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="{% static '/img/arrow.png' %}" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for product in products %}
            <div class="block">
                <a href="#"><img src="{% static product.src %}" alt="">
                    <div class="text">
                        <img src="{% static '/img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.title }}</h4>
                        <p>{{ product.second_title }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}